name: ci-branches

on:
  push:
    branches-ignore:
      - master
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Hub Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: aztfmod 
        # Container registry password
        password: ${{ secrets.docker_registry_password }}
        # Container registry server url
        login-server: https://index.docker.io/v1/
    - name: Build the rover
      run: |        
        set -e
        tag=$(date +"%g%m.%d%H%M")
        docker-compose build
        docker tag rover_rover aztfmod/roverdev:$tag
        docker push aztfmod/roverdev:$tag